import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import { Noto_Sans_JP } from "next/font/google";
import Script from "next/script";

const NotoSansJP = Noto_Sans_JP({
  weight: ["400", "700"],
  // weight: "300",
  preload: true,
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "エンジニアになった元数学教師の記録",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`bg-slate-200 ${NotoSansJP.className} `}>
        <Script src="//cdn.iframe.ly/embed.js" strategy="lazyOnload" />
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow container pt-4 mx-auto">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
